spring:
  datasource:
    url: jdbc:p6spy:h2:~/test;MODE=MySQL
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379

